apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: tutorial
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: "0.1"
          memory: "100Mi"
        limits:
          cpu: "0.1"
          memory: "100Mi"
